name: Branch
run-name: ${{ github.actor }} push ${{ github.event.pull_request.title }}
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Test:
    uses: ./.github/workflows/test.yml
