name: Build
run-name: ${{ github.actor }} kicked off a build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source
        uses: actions/checkout@v4
      - name: Installing bazel
        uses: bazelbuild/setup-bazelisk@v2
      - name: Running tests
        run: |
          bazel test //...
