name: Test
on:
  workflow_call:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source
        uses: actions/checkout@v4
      - name: Installing bazel
        uses: bazelbuild/setup-bazelisk@v2
      - name: Installing bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Running tests
        run: |
          bazel test //...
