name: Test
on:
  workflow_call:
jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source
        uses: actions/checkout@v4
      - name: Installing bazel
        uses: bazelbuild/setup-bazelisk@v2
      - name: Installing bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Running tests
        run: |
          bazel test //...
  Client:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source
        uses: actions/checkout@v4
      # TODO (adu): Add caching here.
      - name: Running tests
        run: |
          cd clients/web-devel
          yarn
          yarn tsc
